import Head from 'next/head'
import Header from '@/components/Header'
import { useRouter } from 'next/router'
import { useContext, useEffect } from 'react'

type LayoutProps = {
  children: React.ReactNode
  title: string
}

export function Layout(props: LayoutProps): React.ReactNode {
  return (
    <>
      <Head>
        <title>{props.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"
        />
      </Head>
      <div style={{ marginBottom: '3.5rem' }}>
        <Header />
      </div>

      {props.children}
    </>
  )
}
